id = "adech"
name = "Adech Theme"
schema_version = 1
version = "0.0.1"
authors = ["Alejandro Polo <alejandrohernandezpolo@gmail.com>"]
description = "Kind of my style theme for Zed"
repository = "https://github.com/Adechlien/adech-theme"
